### ISSUE TITLE
Single gene perturbation

### ISSUE THREAD

**Issue by vittoriofortino84** [MaayanLab/enrichr#21]
Would it be possible to know whether the Single_Gene_Perturbations_from_GEO_down and Single_Gene_Perturbations_from_GEO_up refer to mouse or rat gene perturbations?

**Comment by AviMaayan** [comment]
@vittoriofortino84 you can use the GSE number in the term to find the study on GEO https://www.ncbi.nlm.nih.gov/geo/.
