### ISSUE TITLE
Clustergram Error 404

### ISSUE THREAD

**Issue by bagnacan** [MaayanLab/enrichr#23]
Dear all,
the Clustergram visualization returns the following error:
```
Error
/Enrichr/error (404)
```
To reproduce the error:
- Submit a list of Entrez gene identifiers
- Click on the ``Pathways`` tab
- Select any pathway
- Select ``Clustergram``

The bar chart visualizations work. This holds true also for the color customization, and the re-arrangement of the results according to the different scoring schemes. The only issue I experienced is with the Clustergram.
Can you please help me? 
Thanks for your time.
Andrea

**Comment by maxim-k** [comment]
Dear Andrea,
We had issues with one Clustergrammer database. Now it's fixed.
