### ISSUE TITLE
API library refresh

### ISSUE THREAD

**Issue by danpaulsmith** [MaayanLab/enrichr#24]
Hi,

I've noticed some libraries (2018, 2019) aren't coming through in the API response - but are showing on the Enrichr website. Am I right?

Thanks

**Comment by maxim-k** [comment]
Could you tell us which libraries don't work and a gene list that you submit? For the gene list you can use https://pastebin.com/ or use Enrichr's 'Share' function on the results page.

**Comment by danpaulsmith** [comment]
When retrieving the libraries from this URL:

http://amp.pharm.mssm.edu/Enrichr/json/libraries.json

Looking for GO Biological Process 2018 and KEGG 2019 Human and Wikipathways 2019 Human

**Comment by maxim-k** [comment]
Thank you for pointing this out. This file is manually created to provide library descriptions for one of our apps. We'll update it.
We recommend using https://amp.pharm.mssm.edu/Enrichr/datasetStatistics endpoint with automatically generated library statistics.
